stages:
  - lint
  - build
  - deploy
  - cleanup

image: 
  name: gitlab.praktikum-services.ru:5050/anton-borodinskiy/borodinskiy-momo-store-infra/cpi:latest

variables:
  CHART: momo-chart
  K8S_NAMESPACE: experimental

lint:
  stage: lint
  script:
    - helm lint . --with-subcharts
  needs: []

build:
  stage: build
  script:
    - >
      helm repo add ${CHART}
      --username ${CI_REGISTRY_USER}
      --password ${CI_REGISTRY_PASSWORD}
      ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/stable
    - helm package .
    - helm cm-push ${CHART}*.tgz ${CHART}
