momo-backend:
  image:
    repository: gitlab.praktikum-services.ru:5050/anton-borodinskiy/borodinskiy-momo-store-app/momo-backend
    pullPolicy: Always
    tag: latest

  dockerconfig: "ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogIllXNTBiMjR0WW05eWIyUnBibk5yYVhrNmNUWkVVRzAzZFNzPSIKCQl9Cgl9Cn0="
  
  fullnameOverride: momo-backend

  autoscaling:
    hpa:
      enabled: true

momo-frontend:
  image:
    repository: gitlab.praktikum-services.ru:5050/anton-borodinskiy/borodinskiy-momo-store-app/momo-frontend
    pullPolicy: Always
    tag: latest
  
  dockerconfig: "ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogIllXNTBiMjR0WW05eWIyUnBibk5yYVhrNmNUWkVVRzAzZFNzPSIKCQl9Cgl9Cn0="

  fullnameOverride: momo-frontend

  autoscaling:
    hpa:
      enabled: true

  ingress:
    enabled: true
    hosts:
      - "momo.antonborodinskiy.ru"
    paths:
      - /
    pathType: Prefix
    
  upstream:
    host: momo-backend
    port: "8081"
